// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: employments.sql

package corporatedb

import (
	"context"
	"database/sql"
	"time"
)

const createEmployment = `-- name: CreateEmployment :exec
INSERT INTO
	employments (id, person_id, company_id, department_id, position_id, status, hired_at)
VALUES
	(?, ?, ?, ?, ?, ?, ?)
`

type CreateEmploymentParams struct {
	ID           string         `json:"id"`
	PersonID     string         `json:"personId"`
	CompanyID    string         `json:"companyId"`
	DepartmentID sql.NullString `json:"departmentId"`
	PositionID   string         `json:"positionId"`
	Status       string         `json:"status"`
	HiredAt      time.Time      `json:"hiredAt"`
}

func (q *Queries) CreateEmployment(ctx context.Context, arg CreateEmploymentParams) error {
	_, err := q.db.ExecContext(ctx, createEmployment,
		arg.ID,
		arg.PersonID,
		arg.CompanyID,
		arg.DepartmentID,
		arg.PositionID,
		arg.Status,
		arg.HiredAt,
	)
	return err
}

const getEmploymentByPersonID = `-- name: GetEmploymentByPersonID :many
SELECT
	id,
	person_id,
	company_id,
	department_id,
	position_id,
	phone_work,
	email_work,
	status,
	use_timetrack,
	hired_at,
	dismissed_at,
	role_department,
	created_at
FROM
	employments
WHERE
	person_id = ?
`

type GetEmploymentByPersonIDRow struct {
	ID             string                        `json:"id"`
	PersonID       string                        `json:"personId"`
	CompanyID      string                        `json:"companyId"`
	DepartmentID   sql.NullString                `json:"departmentId"`
	PositionID     string                        `json:"positionId"`
	PhoneWork      sql.NullString                `json:"phoneWork"`
	EmailWork      sql.NullString                `json:"emailWork"`
	Status         string                        `json:"status"`
	UseTimetrack   bool                          `json:"useTimetrack"`
	HiredAt        time.Time                     `json:"hiredAt"`
	DismissedAt    sql.NullTime                  `json:"dismissedAt"`
	RoleDepartment NullEmploymentsRoleDepartment `json:"roleDepartment"`
	CreatedAt      sql.NullTime                  `json:"createdAt"`
}

func (q *Queries) GetEmploymentByPersonID(ctx context.Context, personID string) ([]GetEmploymentByPersonIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getEmploymentByPersonID, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEmploymentByPersonIDRow
	for rows.Next() {
		var i GetEmploymentByPersonIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.CompanyID,
			&i.DepartmentID,
			&i.PositionID,
			&i.PhoneWork,
			&i.EmailWork,
			&i.Status,
			&i.UseTimetrack,
			&i.HiredAt,
			&i.DismissedAt,
			&i.RoleDepartment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
