// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package corporatedb

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type EmploymentsRoleDepartment string

const (
	EmploymentsRoleDepartmentHead        EmploymentsRoleDepartment = "head"
	EmploymentsRoleDepartmentDeputy      EmploymentsRoleDepartment = "deputy"
	EmploymentsRoleDepartmentSubordinate EmploymentsRoleDepartment = "subordinate"
)

func (e *EmploymentsRoleDepartment) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EmploymentsRoleDepartment(s)
	case string:
		*e = EmploymentsRoleDepartment(s)
	default:
		return fmt.Errorf("unsupported scan type for EmploymentsRoleDepartment: %T", src)
	}
	return nil
}

type NullEmploymentsRoleDepartment struct {
	EmploymentsRoleDepartment EmploymentsRoleDepartment `json:"employmentsRoleDepartment"`
	Valid                     bool                      `json:"valid"` // Valid is true if EmploymentsRoleDepartment is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEmploymentsRoleDepartment) Scan(value interface{}) error {
	if value == nil {
		ns.EmploymentsRoleDepartment, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EmploymentsRoleDepartment.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEmploymentsRoleDepartment) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EmploymentsRoleDepartment), nil
}

type Company struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Inn       string         `json:"inn"`
	Kpp       sql.NullString `json:"kpp"`
	CreatedAt sql.NullTime   `json:"createdAt"`
}

type Department struct {
	ID        string         `json:"id"`
	CompanyID string         `json:"companyId"`
	ParentID  sql.NullString `json:"parentId"`
	Name      string         `json:"name"`
	Code      sql.NullString `json:"code"`
	CreatedAt sql.NullTime   `json:"createdAt"`
}

type Employment struct {
	ID             string                        `json:"id"`
	PersonID       string                        `json:"personId"`
	CompanyID      string                        `json:"companyId"`
	DepartmentID   sql.NullString                `json:"departmentId"`
	PositionID     string                        `json:"positionId"`
	PhoneWork      sql.NullString                `json:"phoneWork"`
	EmailWork      sql.NullString                `json:"emailWork"`
	Status         string                        `json:"status"`
	UseTimetrack   bool                          `json:"useTimetrack"`
	HiredAt        time.Time                     `json:"hiredAt"`
	DismissedAt    sql.NullTime                  `json:"dismissedAt"`
	CreatedAt      sql.NullTime                  `json:"createdAt"`
	RoleDepartment NullEmploymentsRoleDepartment `json:"roleDepartment"`
}

type Person struct {
	ID         string         `json:"id"`
	FirstName  string         `json:"firstName"`
	LastName   string         `json:"lastName"`
	Patronymic sql.NullString `json:"patronymic"`
	Birthday   sql.NullTime   `json:"birthday"`
	Snils      sql.NullString `json:"snils"`
	Phone      sql.NullString `json:"phone"`
	Email      sql.NullString `json:"email"`
	AuthUserID sql.NullString `json:"authUserId"`
	CreatedAt  sql.NullTime   `json:"createdAt"`
}

type Position struct {
	ID        string `json:"id"`
	CompanyID string `json:"companyId"`
	Title     string `json:"title"`
}
