// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: persons.sql

package corporatedb

import (
	"context"
	"database/sql"
)

const createPerson = `-- name: CreatePerson :exec
INSERT INTO
	persons (id, first_name, last_name, patronymic, birthday, snils, phone, email, auth_user_id)
VALUES
	(?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreatePersonParams struct {
	ID         string         `json:"id"`
	FirstName  string         `json:"firstName"`
	LastName   string         `json:"lastName"`
	Patronymic sql.NullString `json:"patronymic"`
	Birthday   sql.NullTime   `json:"birthday"`
	Snils      sql.NullString `json:"snils"`
	Phone      sql.NullString `json:"phone"`
	Email      sql.NullString `json:"email"`
	AuthUserID sql.NullString `json:"authUserId"`
}

func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) error {
	_, err := q.db.ExecContext(ctx, createPerson,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Patronymic,
		arg.Birthday,
		arg.Snils,
		arg.Phone,
		arg.Email,
		arg.AuthUserID,
	)
	return err
}

const getPersonByAuthUserID = `-- name: GetPersonByAuthUserID :one
SELECT
	id,
	first_name,
	last_name,
	patronymic,
	birthday,
	snils,
	phone,
	email,
	auth_user_id,
	created_at
FROM
	persons
WHERE
	auth_user_id = ?
`

func (q *Queries) GetPersonByAuthUserID(ctx context.Context, authUserID sql.NullString) (Person, error) {
	row := q.db.QueryRowContext(ctx, getPersonByAuthUserID, authUserID)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Patronymic,
		&i.Birthday,
		&i.Snils,
		&i.Phone,
		&i.Email,
		&i.AuthUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getPersonByID = `-- name: GetPersonByID :one
SELECT
	id,
	first_name,
	last_name,
	patronymic,
	birthday,
	snils,
	phone,
	email,
	auth_user_id,
	created_at
FROM
	persons
WHERE
	id = ?
`

func (q *Queries) GetPersonByID(ctx context.Context, id string) (Person, error) {
	row := q.db.QueryRowContext(ctx, getPersonByID, id)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Patronymic,
		&i.Birthday,
		&i.Snils,
		&i.Phone,
		&i.Email,
		&i.AuthUserID,
		&i.CreatedAt,
	)
	return i, err
}

const updatePersonOnLink = `-- name: UpdatePersonOnLink :exec
UPDATE persons
SET
	first_name = ?,
	last_name = ?,
	patronymic = ?,
	birthday = ?,
	phone = ?,
	email = ?,
	auth_user_id = ?
WHERE
	id = ?
`

type UpdatePersonOnLinkParams struct {
	FirstName  string         `json:"firstName"`
	LastName   string         `json:"lastName"`
	Patronymic sql.NullString `json:"patronymic"`
	Birthday   sql.NullTime   `json:"birthday"`
	Phone      sql.NullString `json:"phone"`
	Email      sql.NullString `json:"email"`
	AuthUserID sql.NullString `json:"authUserId"`
	ID         string         `json:"id"`
}

// Используется в invite.Service.Accept, когда инвайт был выпущен с уже
// существующим person_id: линкует новый auth-аккаунт к существующему
// профилю (вместо создания нового) и одновременно перезаписывает
// редактируемые поля тем, что пользователь подтвердил/поправил в форме
// (см. ValidateResponse.Person — оттуда форма была предзаполнена).
func (q *Queries) UpdatePersonOnLink(ctx context.Context, arg UpdatePersonOnLinkParams) error {
	_, err := q.db.ExecContext(ctx, updatePersonOnLink,
		arg.FirstName,
		arg.LastName,
		arg.Patronymic,
		arg.Birthday,
		arg.Phone,
		arg.Email,
		arg.AuthUserID,
		arg.ID,
	)
	return err
}
