// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package corporatedb

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateEmployment(ctx context.Context, arg CreateEmploymentParams) error
	CreatePerson(ctx context.Context, arg CreatePersonParams) error
	GetEmploymentByPersonID(ctx context.Context, personID string) ([]GetEmploymentByPersonIDRow, error)
	GetPersonByAuthUserID(ctx context.Context, authUserID sql.NullString) (Person, error)
	GetPersonByID(ctx context.Context, id string) (Person, error)
	// Используется в invite.Service.Accept, когда инвайт был выпущен с уже
	// существующим person_id: линкует новый auth-аккаунт к существующему
	// профилю (вместо создания нового) и одновременно перезаписывает
	// редактируемые поля тем, что пользователь подтвердил/поправил в форме
	// (см. ValidateResponse.Person — оттуда форма была предзаполнена).
	UpdatePersonOnLink(ctx context.Context, arg UpdatePersonOnLinkParams) error
}

var _ Querier = (*Queries)(nil)
