// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: genders.sql

package repo

import (
	"context"
)

const getGenderByID = `-- name: GetGenderByID :one
SELECT id, name
FROM genders
WHERE id = ?
`

func (q *Queries) GetGenderByID(ctx context.Context, id string) (Gender, error) {
	row := q.db.QueryRowContext(ctx, getGenderByID, id)
	var i Gender
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listGenders = `-- name: ListGenders :many
SELECT id, name
FROM genders
ORDER BY id
`

func (q *Queries) ListGenders(ctx context.Context) ([]Gender, error) {
	rows, err := q.db.QueryContext(ctx, listGenders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Gender
	for rows.Next() {
		var i Gender
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
