// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package repo

import (
	"context"
	"database/sql"
	"time"
)

const createInvite = `-- name: CreateInvite :exec
INSERT INTO
	invites (id, code, email, person_id, company_id, department_id, position_id, created_by, expires_at)
VALUES
	(?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateInviteParams struct {
	ID           string         `json:"id"`
	Code         string         `json:"code"`
	Email        sql.NullString `json:"email"`
	PersonID     sql.NullString `json:"personId"`
	CompanyID    sql.NullString `json:"companyId"`
	DepartmentID sql.NullString `json:"departmentId"`
	PositionID   sql.NullString `json:"positionId"`
	CreatedBy    sql.NullString `json:"createdBy"`
	ExpiresAt    time.Time      `json:"expiresAt"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) error {
	_, err := q.db.ExecContext(ctx, createInvite,
		arg.ID,
		arg.Code,
		arg.Email,
		arg.PersonID,
		arg.CompanyID,
		arg.DepartmentID,
		arg.PositionID,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	return err
}

const getActiveInviteByEmail = `-- name: GetActiveInviteByEmail :one
SELECT
	id,
	code,
	email,
	person_id,
	company_id,
	department_id,
	position_id,
	created_by,
	user_id,
	used,
	revoked,
	expires_at,
	created_at
FROM
	invites
WHERE
	email = ?
	AND used = 0
	AND revoked = 0
	AND expires_at > UTC_TIMESTAMP()
`

type GetActiveInviteByEmailRow struct {
	ID           string         `json:"id"`
	Code         string         `json:"code"`
	Email        sql.NullString `json:"email"`
	PersonID     sql.NullString `json:"personId"`
	CompanyID    sql.NullString `json:"companyId"`
	DepartmentID sql.NullString `json:"departmentId"`
	PositionID   sql.NullString `json:"positionId"`
	CreatedBy    sql.NullString `json:"createdBy"`
	UserID       sql.NullString `json:"userId"`
	Used         bool           `json:"used"`
	Revoked      bool           `json:"revoked"`
	ExpiresAt    time.Time      `json:"expiresAt"`
	CreatedAt    time.Time      `json:"createdAt"`
}

// Используется при создании инвайта: ищет ещё не использованный, не
// отозванный и не истёкший инвайт на этот email, чтобы отозвать его перед
// выдачей нового (см. invite.Service.Create).
func (q *Queries) GetActiveInviteByEmail(ctx context.Context, email sql.NullString) (GetActiveInviteByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveInviteByEmail, email)
	var i GetActiveInviteByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Email,
		&i.PersonID,
		&i.CompanyID,
		&i.DepartmentID,
		&i.PositionID,
		&i.CreatedBy,
		&i.UserID,
		&i.Used,
		&i.Revoked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInviteByCode = `-- name: GetInviteByCode :one
SELECT
	id,
	code,
	email,
	person_id,
	company_id,
	department_id,
	position_id,
	created_by,
	user_id,
	used,
	revoked,
	expires_at,
	created_at
FROM
	invites
WHERE
	code = ?
`

type GetInviteByCodeRow struct {
	ID           string         `json:"id"`
	Code         string         `json:"code"`
	Email        sql.NullString `json:"email"`
	PersonID     sql.NullString `json:"personId"`
	CompanyID    sql.NullString `json:"companyId"`
	DepartmentID sql.NullString `json:"departmentId"`
	PositionID   sql.NullString `json:"positionId"`
	CreatedBy    sql.NullString `json:"createdBy"`
	UserID       sql.NullString `json:"userId"`
	Used         bool           `json:"used"`
	Revoked      bool           `json:"revoked"`
	ExpiresAt    time.Time      `json:"expiresAt"`
	CreatedAt    time.Time      `json:"createdAt"`
}

func (q *Queries) GetInviteByCode(ctx context.Context, code string) (GetInviteByCodeRow, error) {
	row := q.db.QueryRowContext(ctx, getInviteByCode, code)
	var i GetInviteByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Email,
		&i.PersonID,
		&i.CompanyID,
		&i.DepartmentID,
		&i.PositionID,
		&i.CreatedBy,
		&i.UserID,
		&i.Used,
		&i.Revoked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInviteByID = `-- name: GetInviteByID :one
SELECT
	id,
	code,
	email,
	person_id,
	company_id,
	department_id,
	position_id,
	created_by,
	user_id,
	used,
	revoked,
	expires_at,
	created_at
FROM
	invites
WHERE
	id = ?
`

type GetInviteByIDRow struct {
	ID           string         `json:"id"`
	Code         string         `json:"code"`
	Email        sql.NullString `json:"email"`
	PersonID     sql.NullString `json:"personId"`
	CompanyID    sql.NullString `json:"companyId"`
	DepartmentID sql.NullString `json:"departmentId"`
	PositionID   sql.NullString `json:"positionId"`
	CreatedBy    sql.NullString `json:"createdBy"`
	UserID       sql.NullString `json:"userId"`
	Used         bool           `json:"used"`
	Revoked      bool           `json:"revoked"`
	ExpiresAt    time.Time      `json:"expiresAt"`
	CreatedAt    time.Time      `json:"createdAt"`
}

func (q *Queries) GetInviteByID(ctx context.Context, id string) (GetInviteByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getInviteByID, id)
	var i GetInviteByIDRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Email,
		&i.PersonID,
		&i.CompanyID,
		&i.DepartmentID,
		&i.PositionID,
		&i.CreatedBy,
		&i.UserID,
		&i.Used,
		&i.Revoked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listInvites = `-- name: ListInvites :many
SELECT
	id,
	code,
	email,
	person_id,
	company_id,
	department_id,
	position_id,
	created_by,
	user_id,
	used,
	revoked,
	expires_at,
	created_at
FROM
	invites
ORDER BY
	created_at DESC
`

type ListInvitesRow struct {
	ID           string         `json:"id"`
	Code         string         `json:"code"`
	Email        sql.NullString `json:"email"`
	PersonID     sql.NullString `json:"personId"`
	CompanyID    sql.NullString `json:"companyId"`
	DepartmentID sql.NullString `json:"departmentId"`
	PositionID   sql.NullString `json:"positionId"`
	CreatedBy    sql.NullString `json:"createdBy"`
	UserID       sql.NullString `json:"userId"`
	Used         bool           `json:"used"`
	Revoked      bool           `json:"revoked"`
	ExpiresAt    time.Time      `json:"expiresAt"`
	CreatedAt    time.Time      `json:"createdAt"`
}

// Без пагинации (см. ListAllUsers): фильтрация по search/company_id/
// department_id/position_id и сортировка выполняются в Go, см.
// invite.Service.List.
func (q *Queries) ListInvites(ctx context.Context) ([]ListInvitesRow, error) {
	rows, err := q.db.QueryContext(ctx, listInvites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvitesRow
	for rows.Next() {
		var i ListInvitesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Email,
			&i.PersonID,
			&i.CompanyID,
			&i.DepartmentID,
			&i.PositionID,
			&i.CreatedBy,
			&i.UserID,
			&i.Used,
			&i.Revoked,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInviteUsed = `-- name: MarkInviteUsed :exec
UPDATE invites
SET
	used = 1,
	user_id = ?
WHERE
	id = ?
`

type MarkInviteUsedParams struct {
	UserID sql.NullString `json:"userId"`
	ID     string         `json:"id"`
}

func (q *Queries) MarkInviteUsed(ctx context.Context, arg MarkInviteUsedParams) error {
	_, err := q.db.ExecContext(ctx, markInviteUsed, arg.UserID, arg.ID)
	return err
}

const revokeInvite = `-- name: RevokeInvite :exec
UPDATE invites
SET
	revoked = 1
WHERE
	id = ?
`

func (q *Queries) RevokeInvite(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, revokeInvite, id)
	return err
}
