// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type UsersStatus string

const (
	UsersStatusActive   UsersStatus = "active"
	UsersStatusNoActive UsersStatus = "no-active"
)

func (e *UsersStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsersStatus(s)
	case string:
		*e = UsersStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UsersStatus: %T", src)
	}
	return nil
}

type NullUsersStatus struct {
	UsersStatus UsersStatus `json:"usersStatus"`
	Valid       bool        `json:"valid"` // Valid is true if UsersStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsersStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UsersStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsersStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsersStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsersStatus), nil
}

type Gender struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Invite struct {
	ID           string         `json:"id"`
	Code         string         `json:"code"`
	Email        sql.NullString `json:"email"`
	PersonID     sql.NullString `json:"personId"`
	CompanyID    sql.NullString `json:"companyId"`
	DepartmentID sql.NullString `json:"departmentId"`
	PositionID   sql.NullString `json:"positionId"`
	UserID       sql.NullString `json:"userId"`
	Used         bool           `json:"used"`
	Revoked      bool           `json:"revoked"`
	ExpiresAt    time.Time      `json:"expiresAt"`
	CreatedAt    time.Time      `json:"createdAt"`
	CreatedBy    sql.NullString `json:"createdBy"`
}

type Permission struct {
	ID          string         `json:"id"`
	ServiceID   sql.NullString `json:"serviceId"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	CreatedAt   time.Time      `json:"createdAt"`
}

type Role struct {
	ID          string         `json:"id"`
	ServiceID   sql.NullString `json:"serviceId"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	IsGlobal    bool           `json:"isGlobal"`
	CreatedAt   time.Time      `json:"createdAt"`
}

type RolePermission struct {
	RoleID       string    `json:"roleId"`
	PermissionID string    `json:"permissionId"`
	GrantedAt    time.Time `json:"grantedAt"`
}

type Service struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Prefix      string         `json:"prefix"`
	Theme       sql.NullString `json:"theme"`
	Description string         `json:"description"`
	ImageUrl    sql.NullString `json:"imageUrl"`
	Url         sql.NullString `json:"url"`
	CreatedAt   time.Time      `json:"createdAt"`
	ApiKeyHash  sql.NullString `json:"apiKeyHash"`
}

type Session struct {
	ID        string    `json:"id"`
	TokenHash string    `json:"tokenHash"`
	UserID    string    `json:"userId"`
	ExpiresAt time.Time `json:"expiresAt"`
}

type User struct {
	ID         string         `json:"id"`
	Name       string         `json:"name"`
	Surname    string         `json:"surname"`
	Patronymic sql.NullString `json:"patronymic"`
	Username   string         `json:"username"`
	Password   string         `json:"password"`
	GenderID   string         `json:"genderId"`
	Birthday   time.Time      `json:"birthday"`
	Status     UsersStatus    `json:"status"`
	CreatedAt  time.Time      `json:"createdAt"`
}

type UserRole struct {
	UserID     string    `json:"userId"`
	RoleID     string    `json:"roleId"`
	AssignedAt time.Time `json:"assignedAt"`
}
