// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_resets.sql

package repo

import (
	"context"
	"time"
)

const createPasswordReset = `-- name: CreatePasswordReset :exec
INSERT INTO
	password_resets (id, user_id, token_hash, expires_at)
VALUES
	(?, ?, ?, ?)
`

type CreatePasswordResetParams struct {
	ID        string    `json:"id"`
	UserID    string    `json:"userId"`
	TokenHash string    `json:"tokenHash"`
	ExpiresAt time.Time `json:"expiresAt"`
}

func (q *Queries) CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) error {
	_, err := q.db.ExecContext(ctx, createPasswordReset,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const deletePasswordResetsByUserID = `-- name: DeletePasswordResetsByUserID :exec
DELETE FROM password_resets
WHERE
	user_id = ?
`

// Нужно вызывать перед удалением пользователя (FK password_resets.user_id -> users.id), как DeleteSessionsByUserID.
func (q *Queries) DeletePasswordResetsByUserID(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deletePasswordResetsByUserID, userID)
	return err
}

const getPasswordResetByTokenHash = `-- name: GetPasswordResetByTokenHash :one
SELECT
	id,
	user_id,
	token_hash,
	used,
	expires_at,
	created_at
FROM
	password_resets
WHERE
	token_hash = ?
	AND used = 0
	AND expires_at > UTC_TIMESTAMP()
`

// token хэшируется SHA-256 на стороне Go перед вызовом запроса (как sessions).
func (q *Queries) GetPasswordResetByTokenHash(ctx context.Context, tokenHash string) (PasswordReset, error) {
	row := q.db.QueryRowContext(ctx, getPasswordResetByTokenHash, tokenHash)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Used,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const markPasswordResetUsed = `-- name: MarkPasswordResetUsed :exec
UPDATE password_resets
SET
	used = 1
WHERE
	id = ?
`

func (q *Queries) MarkPasswordResetUsed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markPasswordResetUsed, id)
	return err
}
