// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permissions.sql

package repo

import (
	"context"
	"database/sql"
	"time"
)

const countPermissions = `-- name: CountPermissions :one
SELECT COUNT(*) AS total
FROM permissions
`

func (q *Queries) CountPermissions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPermissions)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countPermissionsByServiceID = `-- name: CountPermissionsByServiceID :one
SELECT COUNT(*) AS total
FROM permissions
WHERE service_id = ?
`

func (q *Queries) CountPermissionsByServiceID(ctx context.Context, serviceID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPermissionsByServiceID, serviceID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createPermission = `-- name: CreatePermission :exec
INSERT INTO permissions (id, service_id, code, name, description, created_at)
VALUES (?, ?, ?, ?, ?, NOW())
`

type CreatePermissionParams struct {
	ID          string         `json:"id"`
	ServiceID   sql.NullString `json:"serviceId"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) error {
	_, err := q.db.ExecContext(ctx, createPermission,
		arg.ID,
		arg.ServiceID,
		arg.Code,
		arg.Name,
		arg.Description,
	)
	return err
}

const deletePermission = `-- name: DeletePermission :exec
DELETE FROM permissions
WHERE id = ?
`

func (q *Queries) DeletePermission(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePermission, id)
	return err
}

const existsUserPermission = `-- name: ExistsUserPermission :one
SELECT EXISTS (
    SELECT 1
    FROM permissions p
    JOIN role_permissions rp ON rp.permission_id = p.id
    JOIN user_roles ur ON ur.role_id = rp.role_id
    WHERE ur.user_id = ?
      AND p.code IN (
        CONCAT(?, ':', ?, ':', ?),
        CONCAT(?, ':', ?, ':all'),
        CONCAT(?, ':all:', ?),
        CONCAT(?, ':all:all'),
        CONCAT('all:', ?, ':', ?),
        CONCAT('all:', ?, ':all'),
        CONCAT('all:all:', ?),
        'all:all:all'
      )
    LIMIT 1
) AS has_permission
`

type ExistsUserPermissionParams struct {
	UserID    string      `json:"userId"`
	CONCAT    interface{} `json:"CONCAT"`
	CONCAT_2  interface{} `json:"CONCAT2"`
	CONCAT_3  interface{} `json:"CONCAT3"`
	CONCAT_4  interface{} `json:"CONCAT4"`
	CONCAT_5  interface{} `json:"CONCAT5"`
	CONCAT_6  interface{} `json:"CONCAT6"`
	CONCAT_7  interface{} `json:"CONCAT7"`
	CONCAT_8  interface{} `json:"CONCAT8"`
	CONCAT_9  interface{} `json:"CONCAT9"`
	CONCAT_10 interface{} `json:"CONCAT10"`
	CONCAT_11 interface{} `json:"CONCAT11"`
	CONCAT_12 interface{} `json:"CONCAT12"`
}

// Проверка наличия разрешения у пользователя с учётом всех wildcard-комбинаций
// сегментов "service:entity:action".
func (q *Queries) ExistsUserPermission(ctx context.Context, arg ExistsUserPermissionParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsUserPermission,
		arg.UserID,
		arg.CONCAT,
		arg.CONCAT_2,
		arg.CONCAT_3,
		arg.CONCAT_4,
		arg.CONCAT_5,
		arg.CONCAT_6,
		arg.CONCAT_7,
		arg.CONCAT_8,
		arg.CONCAT_9,
		arg.CONCAT_10,
		arg.CONCAT_11,
		arg.CONCAT_12,
	)
	var has_permission bool
	err := row.Scan(&has_permission)
	return has_permission, err
}

const getPermissionByCode = `-- name: GetPermissionByCode :one
SELECT id, service_id, code, name, description, created_at
FROM permissions
WHERE code = ?
`

func (q *Queries) GetPermissionByCode(ctx context.Context, code string) (Permission, error) {
	row := q.db.QueryRowContext(ctx, getPermissionByCode, code)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getPermissionByID = `-- name: GetPermissionByID :one
SELECT id, service_id, code, name, description, created_at
FROM permissions
WHERE id = ?
`

func (q *Queries) GetPermissionByID(ctx context.Context, id string) (Permission, error) {
	row := q.db.QueryRowContext(ctx, getPermissionByID, id)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listAllPermissions = `-- name: ListAllPermissions :many
SELECT p.id, p.service_id, p.code, p.name, p.description, p.created_at, s.name AS service_name
FROM permissions p
LEFT JOIN services s ON s.id = p.service_id
`

type ListAllPermissionsRow struct {
	ID          string         `json:"id"`
	ServiceID   sql.NullString `json:"serviceId"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	CreatedAt   time.Time      `json:"createdAt"`
	ServiceName sql.NullString `json:"serviceName"`
}

// Без пагинации: используется, например, при сборе информации о глобальной роли.
func (q *Queries) ListAllPermissions(ctx context.Context) ([]ListAllPermissionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllPermissionsRow
	for rows.Next() {
		var i ListAllPermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.ServiceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllPermissionsByServiceID = `-- name: ListAllPermissionsByServiceID :many
SELECT p.id, p.service_id, p.code, p.name, p.description, p.created_at, s.name AS service_name
FROM permissions p
LEFT JOIN services s ON s.id = p.service_id
WHERE p.service_id = ?
`

type ListAllPermissionsByServiceIDRow struct {
	ID          string         `json:"id"`
	ServiceID   sql.NullString `json:"serviceId"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	CreatedAt   time.Time      `json:"createdAt"`
	ServiceName sql.NullString `json:"serviceName"`
}

// Без пагинации: используется при сборе информации о роли, привязанной к сервису.
func (q *Queries) ListAllPermissionsByServiceID(ctx context.Context, serviceID sql.NullString) ([]ListAllPermissionsByServiceIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllPermissionsByServiceID, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllPermissionsByServiceIDRow
	for rows.Next() {
		var i ListAllPermissionsByServiceIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.ServiceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, service_id, code, name, description, created_at
FROM permissions
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListPermissionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPermissions(ctx context.Context, arg ListPermissionsParams) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, listPermissions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsByServiceID = `-- name: ListPermissionsByServiceID :many
SELECT id, service_id, code, name, description, created_at
FROM permissions
WHERE service_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListPermissionsByServiceIDParams struct {
	ServiceID sql.NullString `json:"serviceId"`
	Limit     int32          `json:"limit"`
	Offset    int32          `json:"offset"`
}

func (q *Queries) ListPermissionsByServiceID(ctx context.Context, arg ListPermissionsByServiceIDParams) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, listPermissionsByServiceID, arg.ServiceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsByUserID = `-- name: ListPermissionsByUserID :many
SELECT DISTINCT p.id, p.service_id, p.code, p.name, p.description, p.created_at
FROM permissions p
JOIN role_permissions rp ON rp.permission_id = p.id
JOIN user_roles ur ON ur.role_id = rp.role_id
WHERE ur.user_id = ?
`

// Все разрешения, доступные пользователю через все его роли.
func (q *Queries) ListPermissionsByUserID(ctx context.Context, userID string) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, listPermissionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsByUserIDAndServiceID = `-- name: ListPermissionsByUserIDAndServiceID :many
SELECT DISTINCT p.id, p.service_id, p.code, p.name, p.description, p.created_at
FROM permissions p
JOIN role_permissions rp ON rp.permission_id = p.id
JOIN user_roles ur ON ur.role_id = rp.role_id
WHERE ur.user_id = ?
  AND (
    p.service_id = ?
    OR p.code LIKE CONCAT(?, ':%')
    OR p.code LIKE 'all:%'
  )
`

type ListPermissionsByUserIDAndServiceIDParams struct {
	UserID    string         `json:"userId"`
	ServiceID sql.NullString `json:"serviceId"`
	CONCAT    interface{}    `json:"CONCAT"`
}

// Разрешения пользователя для конкретного сервиса с учётом wildcard-кодов
// вида "all:all:all" и "<service_name>:all:all".
func (q *Queries) ListPermissionsByUserIDAndServiceID(ctx context.Context, arg ListPermissionsByUserIDAndServiceIDParams) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, listPermissionsByUserIDAndServiceID, arg.UserID, arg.ServiceID, arg.CONCAT)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePermission = `-- name: UpdatePermission :exec
UPDATE permissions
SET service_id  = ?,
    code        = ?,
    name        = ?,
    description = ?
WHERE id = ?
`

type UpdatePermissionParams struct {
	ServiceID   sql.NullString `json:"serviceId"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdatePermission(ctx context.Context, arg UpdatePermissionParams) error {
	_, err := q.db.ExecContext(ctx, updatePermission,
		arg.ServiceID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.ID,
	)
	return err
}
