// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permissions.sql

package repo

import (
	"context"
	"database/sql"
	"time"
)

const countPermissions = `-- name: CountPermissions :one
SELECT
	COUNT(*) AS total
FROM
	permissions p
	LEFT JOIN services s ON s.id = p.service_id
WHERE
	CAST(? AS char) IS NULL
	OR p.code LIKE CONCAT('%', CAST(? AS char), '%')
	OR p.name LIKE CONCAT('%', CAST(? AS char), '%')
	OR p.description LIKE CONCAT('%', CAST(? AS char), '%')
	OR s.name LIKE CONCAT('%', CAST(? AS char), '%')
`

type CountPermissionsParams struct {
	Search interface{} `json:"search"`
}

func (q *Queries) CountPermissions(ctx context.Context, arg CountPermissionsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPermissions,
		arg.Search,
		arg.Search,
		arg.Search,
		arg.Search,
		arg.Search,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countPermissionsByServiceID = `-- name: CountPermissionsByServiceID :one
SELECT
	COUNT(*) AS total
FROM
	permissions p
WHERE
	p.service_id = ?
	AND (
		CAST(? AS char) IS NULL
		OR p.code LIKE CONCAT('%', CAST(? AS char), '%')
		OR p.name LIKE CONCAT('%', CAST(? AS char), '%')
		OR p.description LIKE CONCAT('%', CAST(? AS char), '%')
	)
`

type CountPermissionsByServiceIDParams struct {
	ServiceID sql.NullString `json:"serviceId"`
	Search    interface{}    `json:"search"`
}

func (q *Queries) CountPermissionsByServiceID(ctx context.Context, arg CountPermissionsByServiceIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPermissionsByServiceID,
		arg.ServiceID,
		arg.Search,
		arg.Search,
		arg.Search,
		arg.Search,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createPermission = `-- name: CreatePermission :exec
INSERT INTO
	permissions (id, service_id, code, name, description, created_at)
VALUES
	(?, ?, ?, ?, ?, NOW())
`

type CreatePermissionParams struct {
	ID          string         `json:"id"`
	ServiceID   sql.NullString `json:"serviceId"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) error {
	_, err := q.db.ExecContext(ctx, createPermission,
		arg.ID,
		arg.ServiceID,
		arg.Code,
		arg.Name,
		arg.Description,
	)
	return err
}

const deletePermission = `-- name: DeletePermission :exec
DELETE FROM permissions
WHERE
	id = ?
`

func (q *Queries) DeletePermission(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePermission, id)
	return err
}

const existsUserPermission = `-- name: ExistsUserPermission :one
SELECT
	EXISTS (
		SELECT
			1
		FROM
			permissions p
			JOIN role_permissions rp ON rp.permission_id = p.id
			JOIN user_roles ur ON ur.role_id = rp.role_id
		WHERE
			ur.user_id = ?
			AND p.code IN (
				CONCAT(CAST(? AS char), ':', CAST(? AS char), ':', CAST(? AS char)),
				CONCAT(CAST(? AS char), ':', CAST(? AS char), ':all'),
				CONCAT(CAST(? AS char), ':all:', CAST(? AS char)),
				CONCAT(CAST(? AS char), ':all:all'),
				CONCAT('all:', CAST(? AS char), ':', CAST(? AS char)),
				CONCAT('all:', CAST(? AS char), ':all'),
				CONCAT('all:all:', CAST(? AS char)),
				'all:all:all'
			)
		LIMIT
			1
	) AS has_permission
`

type ExistsUserPermissionParams struct {
	UserID  string      `json:"userId"`
	Service interface{} `json:"service"`
	Entity  interface{} `json:"entity"`
	Action  interface{} `json:"action"`
}

// Проверка наличия разрешения у пользователя с учётом всех wildcard-комбинаций
// сегментов "service:entity:action". Каждый sqlc.arg(...) используется несколько
// раз, но CAST(... AS CHAR) даёт sqlc однозначный тип (string), поэтому в
// сгенерированных параметрах будет ровно 4 понятных поля, а не CONCAT_2..CONCAT_12.
func (q *Queries) ExistsUserPermission(ctx context.Context, arg ExistsUserPermissionParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsUserPermission,
		arg.UserID,
		arg.Service,
		arg.Entity,
		arg.Action,
		arg.Service,
		arg.Entity,
		arg.Service,
		arg.Action,
		arg.Service,
		arg.Entity,
		arg.Action,
		arg.Entity,
		arg.Action,
	)
	var has_permission bool
	err := row.Scan(&has_permission)
	return has_permission, err
}

const getPermissionByCode = `-- name: GetPermissionByCode :one
SELECT
	p.id,
	p.service_id,
	p.code,
	p.name,
	p.description,
	p.created_at,
	s.name AS service_name
FROM
	permissions p
	LEFT JOIN services s ON s.id = p.service_id
WHERE
	p.code = ?
`

type GetPermissionByCodeRow struct {
	ID          string         `json:"id"`
	ServiceID   sql.NullString `json:"serviceId"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	CreatedAt   time.Time      `json:"createdAt"`
	ServiceName sql.NullString `json:"serviceName"`
}

func (q *Queries) GetPermissionByCode(ctx context.Context, code string) (GetPermissionByCodeRow, error) {
	row := q.db.QueryRowContext(ctx, getPermissionByCode, code)
	var i GetPermissionByCodeRow
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.ServiceName,
	)
	return i, err
}

const getPermissionByID = `-- name: GetPermissionByID :one
SELECT
	p.id,
	p.service_id,
	p.code,
	p.name,
	p.description,
	p.created_at,
	s.name AS service_name
FROM
	permissions p
	LEFT JOIN services s ON s.id = p.service_id
WHERE
	p.id = ?
`

type GetPermissionByIDRow struct {
	ID          string         `json:"id"`
	ServiceID   sql.NullString `json:"serviceId"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	CreatedAt   time.Time      `json:"createdAt"`
	ServiceName sql.NullString `json:"serviceName"`
}

func (q *Queries) GetPermissionByID(ctx context.Context, id string) (GetPermissionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPermissionByID, id)
	var i GetPermissionByIDRow
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.ServiceName,
	)
	return i, err
}

const listAllPermissions = `-- name: ListAllPermissions :many
SELECT
	p.id,
	p.service_id,
	p.code,
	p.name,
	p.description,
	p.created_at,
	s.name AS service_name
FROM
	permissions p
	LEFT JOIN services s ON s.id = p.service_id
`

type ListAllPermissionsRow struct {
	ID          string         `json:"id"`
	ServiceID   sql.NullString `json:"serviceId"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	CreatedAt   time.Time      `json:"createdAt"`
	ServiceName sql.NullString `json:"serviceName"`
}

func (q *Queries) ListAllPermissions(ctx context.Context) ([]ListAllPermissionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllPermissionsRow
	for rows.Next() {
		var i ListAllPermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.ServiceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllPermissionsByServiceID = `-- name: ListAllPermissionsByServiceID :many
SELECT
	p.id,
	p.service_id,
	p.code,
	p.name,
	p.description,
	p.created_at,
	s.name AS service_name
FROM
	permissions p
	LEFT JOIN services s ON s.id = p.service_id
WHERE
	p.service_id = ?
`

type ListAllPermissionsByServiceIDRow struct {
	ID          string         `json:"id"`
	ServiceID   sql.NullString `json:"serviceId"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	CreatedAt   time.Time      `json:"createdAt"`
	ServiceName sql.NullString `json:"serviceName"`
}

func (q *Queries) ListAllPermissionsByServiceID(ctx context.Context, serviceID sql.NullString) ([]ListAllPermissionsByServiceIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllPermissionsByServiceID, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllPermissionsByServiceIDRow
	for rows.Next() {
		var i ListAllPermissionsByServiceIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.ServiceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissions = `-- name: ListPermissions :many
SELECT
	p.id,
	p.service_id,
	p.code,
	p.name,
	p.description,
	p.created_at,
	s.name AS service_name
FROM
	permissions p
	LEFT JOIN services s ON s.id = p.service_id
WHERE
	CAST(? AS char) IS NULL
	OR p.code LIKE CONCAT('%', CAST(? AS char), '%')
	OR p.name LIKE CONCAT('%', CAST(? AS char), '%')
	OR p.description LIKE CONCAT('%', CAST(? AS char), '%')
	OR s.name LIKE CONCAT('%', CAST(? AS char), '%')
ORDER BY
	CASE
		WHEN CAST(? AS char) = 'asc' THEN CASE CAST(? AS char)
			WHEN 'code' THEN CAST(p.code AS char)
			WHEN 'name' THEN CAST(p.name AS char)
			WHEN 'description' THEN CAST(p.description AS char)
			WHEN 'service_name' THEN CAST(s.name AS char)
			ELSE CAST(p.created_at AS char)
		END
	END ASC,
	CASE
		WHEN CAST(? AS char) = 'desc' THEN CASE CAST(? AS char)
			WHEN 'code' THEN CAST(p.code AS char)
			WHEN 'name' THEN CAST(p.name AS char)
			WHEN 'description' THEN CAST(p.description AS char)
			WHEN 'service_name' THEN CAST(s.name AS char)
			ELSE CAST(p.created_at AS char)
		END
	END DESC
LIMIT
	?
OFFSET
	?
`

type ListPermissionsParams struct {
	Search  interface{} `json:"search"`
	SortDir interface{} `json:"sortDir"`
	SortBy  interface{} `json:"sortBy"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type ListPermissionsRow struct {
	ID          string         `json:"id"`
	ServiceID   sql.NullString `json:"serviceId"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	CreatedAt   time.Time      `json:"createdAt"`
	ServiceName sql.NullString `json:"serviceName"`
}

// search: поиск по code/name/description/имени сервиса (LIKE, NULL — без фильтра).
// sort_by/sort_dir: колонка (code/name/description/service_name/created_at,
// иначе — created_at) и направление сортировки ("asc" — иначе "desc") задаются
// в Go на белом списке (см. query.QuerySort), в SQL любое неизвестное значение
// sort_by безопасно попадает в ветку ELSE.
func (q *Queries) ListPermissions(ctx context.Context, arg ListPermissionsParams) ([]ListPermissionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPermissions,
		arg.Search,
		arg.Search,
		arg.Search,
		arg.Search,
		arg.Search,
		arg.SortDir,
		arg.SortBy,
		arg.SortDir,
		arg.SortBy,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPermissionsRow
	for rows.Next() {
		var i ListPermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.ServiceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsByServiceID = `-- name: ListPermissionsByServiceID :many
SELECT
	p.id,
	p.service_id,
	p.code,
	p.name,
	p.description,
	p.created_at,
	s.name AS service_name
FROM
	permissions p
	LEFT JOIN services s ON s.id = p.service_id
WHERE
	p.service_id = ?
	AND (
		CAST(? AS char) IS NULL
		OR p.code LIKE CONCAT('%', CAST(? AS char), '%')
		OR p.name LIKE CONCAT('%', CAST(? AS char), '%')
		OR p.description LIKE CONCAT('%', CAST(? AS char), '%')
	)
ORDER BY
	CASE
		WHEN CAST(? AS char) = 'asc' THEN CASE CAST(? AS char)
			WHEN 'code' THEN CAST(p.code AS char)
			WHEN 'name' THEN CAST(p.name AS char)
			WHEN 'description' THEN CAST(p.description AS char)
			WHEN 'service_name' THEN CAST(s.name AS char)
			ELSE CAST(p.created_at AS char)
		END
	END ASC,
	CASE
		WHEN CAST(? AS char) = 'desc' THEN CASE CAST(? AS char)
			WHEN 'code' THEN CAST(p.code AS char)
			WHEN 'name' THEN CAST(p.name AS char)
			WHEN 'description' THEN CAST(p.description AS char)
			WHEN 'service_name' THEN CAST(s.name AS char)
			ELSE CAST(p.created_at AS char)
		END
	END DESC
LIMIT
	?
OFFSET
	?
`

type ListPermissionsByServiceIDParams struct {
	ServiceID sql.NullString `json:"serviceId"`
	Search    interface{}    `json:"search"`
	SortDir   interface{}    `json:"sortDir"`
	SortBy    interface{}    `json:"sortBy"`
	Limit     int32          `json:"limit"`
	Offset    int32          `json:"offset"`
}

type ListPermissionsByServiceIDRow struct {
	ID          string         `json:"id"`
	ServiceID   sql.NullString `json:"serviceId"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	CreatedAt   time.Time      `json:"createdAt"`
	ServiceName sql.NullString `json:"serviceName"`
}

func (q *Queries) ListPermissionsByServiceID(ctx context.Context, arg ListPermissionsByServiceIDParams) ([]ListPermissionsByServiceIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listPermissionsByServiceID,
		arg.ServiceID,
		arg.Search,
		arg.Search,
		arg.Search,
		arg.Search,
		arg.SortDir,
		arg.SortBy,
		arg.SortDir,
		arg.SortBy,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPermissionsByServiceIDRow
	for rows.Next() {
		var i ListPermissionsByServiceIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.ServiceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsByUserID = `-- name: ListPermissionsByUserID :many
SELECT DISTINCT
	p.id,
	p.service_id,
	p.code,
	p.name,
	p.description,
	p.created_at
FROM
	permissions p
	JOIN role_permissions rp ON rp.permission_id = p.id
	JOIN user_roles ur ON ur.role_id = rp.role_id
WHERE
	ur.user_id = ?
`

func (q *Queries) ListPermissionsByUserID(ctx context.Context, userID string) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, listPermissionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsByUserIDAndServiceID = `-- name: ListPermissionsByUserIDAndServiceID :many
SELECT DISTINCT
	p.id,
	p.service_id,
	p.code,
	p.name,
	p.description,
	p.created_at
FROM
	permissions p
	JOIN role_permissions rp ON rp.permission_id = p.id
	JOIN user_roles ur ON ur.role_id = rp.role_id
WHERE
	ur.user_id = ?
	AND (
		p.service_id = ?
		OR p.code like CONCAT(CAST(? AS char), ':%')
		OR p.code like 'all:%'
	)
`

type ListPermissionsByUserIDAndServiceIDParams struct {
	UserID      string         `json:"userId"`
	ServiceID   sql.NullString `json:"serviceId"`
	ServiceName interface{}    `json:"serviceName"`
}

// Разрешения пользователя для конкретного сервиса с учётом wildcard-кодов
// вида "all:all:all" и "<service_name>:all:all". sqlc.arg + CAST(...AS CHAR),
// чтобы sqlc корректно типизировал повторяющийся параметр service_name.
func (q *Queries) ListPermissionsByUserIDAndServiceID(ctx context.Context, arg ListPermissionsByUserIDAndServiceIDParams) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, listPermissionsByUserIDAndServiceID, arg.UserID, arg.ServiceID, arg.ServiceName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePermission = `-- name: UpdatePermission :exec
UPDATE permissions
SET
	service_id = ?,
	code = ?,
	name = ?,
	description = ?
WHERE
	id = ?
`

type UpdatePermissionParams struct {
	ServiceID   sql.NullString `json:"serviceId"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdatePermission(ctx context.Context, arg UpdatePermissionParams) error {
	_, err := q.db.ExecContext(ctx, updatePermission,
		arg.ServiceID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.ID,
	)
	return err
}
