// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddPermissionToRole(ctx context.Context, arg AddPermissionToRoleParams) error
	AddRoleToUser(ctx context.Context, arg AddRoleToUserParams) error
	CountPermissions(ctx context.Context) (int64, error)
	CountPermissionsByServiceID(ctx context.Context, serviceID sql.NullString) (int64, error)
	CountRoles(ctx context.Context) (int64, error)
	CountRolesByServiceID(ctx context.Context, serviceID sql.NullString) (int64, error)
	CountServices(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CountUsersByServiceID(ctx context.Context, serviceID sql.NullString) (int64, error)
	CreatePermission(ctx context.Context, arg CreatePermissionParams) error
	CreateRole(ctx context.Context, arg CreateRoleParams) error
	CreateService(ctx context.Context, arg CreateServiceParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeletePermission(ctx context.Context, id string) error
	DeleteRole(ctx context.Context, id string) error
	DeleteService(ctx context.Context, id string) error
	DeleteSessionByID(ctx context.Context, id string) error
	// Удаление сессии по хэшу токена (logout). Токен хэшируется SHA-256 на стороне Go.
	DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error
	// Нужно вызывать перед удалением пользователя (FK sessions.user_id -> users.id).
	DeleteSessionsByUserID(ctx context.Context, userID string) error
	DeleteUser(ctx context.Context, id string) error
	// Проверка наличия разрешения у пользователя с учётом всех wildcard-комбинаций
	// сегментов "service:entity:action". Каждый sqlc.arg(...) используется несколько
	// раз, но CAST(... AS CHAR) даёт sqlc однозначный тип (string), поэтому в
	// сгенерированных параметрах будет ровно 4 понятных поля, а не CONCAT_2..CONCAT_12.
	ExistsUserPermission(ctx context.Context, arg ExistsUserPermissionParams) (bool, error)
	GetGenderByID(ctx context.Context, id string) (Gender, error)
	GetPermissionByCode(ctx context.Context, code string) (GetPermissionByCodeRow, error)
	GetPermissionByID(ctx context.Context, id string) (GetPermissionByIDRow, error)
	GetRoleByID(ctx context.Context, id string) (Role, error)
	GetServiceByAPIKeyHash(ctx context.Context, apiKeyHash sql.NullString) (GetServiceByAPIKeyHashRow, error)
	GetServiceByID(ctx context.Context, id string) (GetServiceByIDRow, error)
	// token хэшируется SHA-256 на стороне Go перед вызовом запроса.
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error)
	GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error)
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
	ListAllPermissions(ctx context.Context) ([]ListAllPermissionsRow, error)
	ListAllPermissionsByServiceID(ctx context.Context, serviceID sql.NullString) ([]ListAllPermissionsByServiceIDRow, error)
	ListAllUsers(ctx context.Context) ([]ListAllUsersRow, error)
	ListGenders(ctx context.Context) ([]Gender, error)
	ListPermissions(ctx context.Context, arg ListPermissionsParams) ([]ListPermissionsRow, error)
	ListPermissionsByServiceID(ctx context.Context, arg ListPermissionsByServiceIDParams) ([]ListPermissionsByServiceIDRow, error)
	ListPermissionsByUserID(ctx context.Context, userID string) ([]Permission, error)
	// Разрешения пользователя для конкретного сервиса с учётом wildcard-кодов
	// вида "all:all:all" и "<service_name>:all:all". sqlc.arg + CAST(...AS CHAR),
	// чтобы sqlc корректно типизировал повторяющийся параметр service_name.
	ListPermissionsByUserIDAndServiceID(ctx context.Context, arg ListPermissionsByUserIDAndServiceIDParams) ([]Permission, error)
	ListPermissionsForRole(ctx context.Context, roleID string) ([]ListPermissionsForRoleRow, error)
	ListRoles(ctx context.Context, arg ListRolesParams) ([]Role, error)
	ListRolesByServiceID(ctx context.Context, arg ListRolesByServiceIDParams) ([]Role, error)
	ListRolesForUser(ctx context.Context, userID string) ([]Role, error)
	ListRolesWithCounts(ctx context.Context, arg ListRolesWithCountsParams) ([]ListRolesWithCountsRow, error)
	ListRolesWithCountsByServiceID(ctx context.Context, arg ListRolesWithCountsByServiceIDParams) ([]ListRolesWithCountsByServiceIDRow, error)
	ListServices(ctx context.Context, arg ListServicesParams) ([]ListServicesRow, error)
	// Сервисы, доступные пользователю через его роли:
	// либо роль привязана к конкретному сервису, либо роль глобальная (service_id IS NULL).
	ListServicesByUserID(ctx context.Context, userID string) ([]ListServicesByUserIDRow, error)
	ListUsedPermissionIDsForRole(ctx context.Context, roleID string) ([]string, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	ListUsersByServiceID(ctx context.Context, arg ListUsersByServiceIDParams) ([]ListUsersByServiceIDRow, error)
	ListUsersWithRole(ctx context.Context, roleID string) ([]ListUsersWithRoleRow, error)
	RemovePermissionFromRole(ctx context.Context, arg RemovePermissionFromRoleParams) error
	RemoveRoleFromUser(ctx context.Context, arg RemoveRoleFromUserParams) error
	RevokeServiceAPIKey(ctx context.Context, id string) error
	SetServiceAPIKeyHash(ctx context.Context, arg SetServiceAPIKeyHashParams) error
	UpdatePermission(ctx context.Context, arg UpdatePermissionParams) error
	UpdateRole(ctx context.Context, arg UpdateRoleParams) error
	UpdateService(ctx context.Context, arg UpdateServiceParams) error
	// Частичное обновление: sqlc.narg-поля, для которых передан NULL, остаются без изменений.
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
