// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package repo

import (
	"context"
	"database/sql"
	"time"
)

const addPermissionToRole = `-- name: AddPermissionToRole :exec
INSERT INTO
	role_permissions (role_id, permission_id, granted_at)
VALUES
	(?, ?, NOW())
`

type AddPermissionToRoleParams struct {
	RoleID       string `json:"roleId"`
	PermissionID string `json:"permissionId"`
}

func (q *Queries) AddPermissionToRole(ctx context.Context, arg AddPermissionToRoleParams) error {
	_, err := q.db.ExecContext(ctx, addPermissionToRole, arg.RoleID, arg.PermissionID)
	return err
}

const countRoles = `-- name: CountRoles :one
SELECT
	COUNT(*) AS total
FROM
	roles
`

func (q *Queries) CountRoles(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRoles)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countRolesByServiceID = `-- name: CountRolesByServiceID :one
SELECT
	COUNT(*) AS total
FROM
	roles
WHERE
	service_id = ?
`

func (q *Queries) CountRolesByServiceID(ctx context.Context, serviceID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRolesByServiceID, serviceID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createRole = `-- name: CreateRole :exec
INSERT INTO
	roles (id, service_id, name, description, is_global, created_at)
VALUES
	(?, ?, ?, ?, ?, NOW())
`

type CreateRoleParams struct {
	ID          string         `json:"id"`
	ServiceID   sql.NullString `json:"serviceId"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	IsGlobal    bool           `json:"isGlobal"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) error {
	_, err := q.db.ExecContext(ctx, createRole,
		arg.ID,
		arg.ServiceID,
		arg.Name,
		arg.Description,
		arg.IsGlobal,
	)
	return err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles
WHERE
	id = ?
`

func (q *Queries) DeleteRole(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRole, id)
	return err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT
	id,
	service_id,
	name,
	description,
	is_global,
	created_at
FROM
	roles
WHERE
	id = ?
`

func (q *Queries) GetRoleByID(ctx context.Context, id string) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Name,
		&i.Description,
		&i.IsGlobal,
		&i.CreatedAt,
	)
	return i, err
}

const listPermissionsForRole = `-- name: ListPermissionsForRole :many
SELECT
	p.id,
	p.service_id,
	p.code,
	p.name,
	p.description,
	p.created_at,
	s.name AS service_name
FROM
	permissions p
	JOIN role_permissions rp ON rp.permission_id = p.id
	LEFT JOIN services s ON s.id = p.service_id
WHERE
	rp.role_id = ?
`

type ListPermissionsForRoleRow struct {
	ID          string         `json:"id"`
	ServiceID   sql.NullString `json:"serviceId"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	CreatedAt   time.Time      `json:"createdAt"`
	ServiceName sql.NullString `json:"serviceName"`
}

func (q *Queries) ListPermissionsForRole(ctx context.Context, roleID string) ([]ListPermissionsForRoleRow, error) {
	rows, err := q.db.QueryContext(ctx, listPermissionsForRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPermissionsForRoleRow
	for rows.Next() {
		var i ListPermissionsForRoleRow
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.ServiceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT
	id,
	service_id,
	name,
	description,
	is_global,
	created_at
FROM
	roles
ORDER BY
	created_at DESC
LIMIT
	?
OFFSET
	?
`

type ListRolesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListRoles(ctx context.Context, arg ListRolesParams) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, listRoles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Name,
			&i.Description,
			&i.IsGlobal,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesByServiceID = `-- name: ListRolesByServiceID :many
SELECT
	id,
	service_id,
	name,
	description,
	is_global,
	created_at
FROM
	roles
WHERE
	service_id = ?
ORDER BY
	created_at DESC
LIMIT
	?
OFFSET
	?
`

type ListRolesByServiceIDParams struct {
	ServiceID sql.NullString `json:"serviceId"`
	Limit     int32          `json:"limit"`
	Offset    int32          `json:"offset"`
}

func (q *Queries) ListRolesByServiceID(ctx context.Context, arg ListRolesByServiceIDParams) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, listRolesByServiceID, arg.ServiceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Name,
			&i.Description,
			&i.IsGlobal,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesWithCounts = `-- name: ListRolesWithCounts :many
SELECT
	r.id,
	r.service_id,
	r.name,
	r.description,
	r.is_global,
	r.created_at,
	COALESCE(uc.user_count, 0) AS user_count,
	COALESCE(pc.permission_count, 0) AS permission_count
FROM
	roles r
	LEFT JOIN (
		SELECT
			role_id,
			COUNT(user_id) AS user_count
		FROM
			user_roles
		GROUP BY
			role_id
	) uc ON uc.role_id = r.id
	LEFT JOIN (
		SELECT
			role_id,
			COUNT(permission_id) AS permission_count
		FROM
			role_permissions
		GROUP BY
			role_id
	) pc ON pc.role_id = r.id
ORDER BY
	r.created_at DESC
LIMIT
	?
OFFSET
	?
`

type ListRolesWithCountsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListRolesWithCountsRow struct {
	ID              string         `json:"id"`
	ServiceID       sql.NullString `json:"serviceId"`
	Name            string         `json:"name"`
	Description     string         `json:"description"`
	IsGlobal        bool           `json:"isGlobal"`
	CreatedAt       time.Time      `json:"createdAt"`
	UserCount       int64          `json:"userCount"`
	PermissionCount int64          `json:"permissionCount"`
}

func (q *Queries) ListRolesWithCounts(ctx context.Context, arg ListRolesWithCountsParams) ([]ListRolesWithCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRolesWithCounts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRolesWithCountsRow
	for rows.Next() {
		var i ListRolesWithCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Name,
			&i.Description,
			&i.IsGlobal,
			&i.CreatedAt,
			&i.UserCount,
			&i.PermissionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesWithCountsByServiceID = `-- name: ListRolesWithCountsByServiceID :many
SELECT
	r.id,
	r.service_id,
	r.name,
	r.description,
	r.is_global,
	r.created_at,
	COALESCE(uc.user_count, 0) AS user_count,
	COALESCE(pc.permission_count, 0) AS permission_count
FROM
	roles r
	LEFT JOIN (
		SELECT
			role_id,
			COUNT(user_id) AS user_count
		FROM
			user_roles
		GROUP BY
			role_id
	) uc ON uc.role_id = r.id
	LEFT JOIN (
		SELECT
			role_id,
			COUNT(permission_id) AS permission_count
		FROM
			role_permissions
		GROUP BY
			role_id
	) pc ON pc.role_id = r.id
WHERE
	r.service_id = ?
ORDER BY
	r.created_at DESC
LIMIT
	?
OFFSET
	?
`

type ListRolesWithCountsByServiceIDParams struct {
	ServiceID sql.NullString `json:"serviceId"`
	Limit     int32          `json:"limit"`
	Offset    int32          `json:"offset"`
}

type ListRolesWithCountsByServiceIDRow struct {
	ID              string         `json:"id"`
	ServiceID       sql.NullString `json:"serviceId"`
	Name            string         `json:"name"`
	Description     string         `json:"description"`
	IsGlobal        bool           `json:"isGlobal"`
	CreatedAt       time.Time      `json:"createdAt"`
	UserCount       int64          `json:"userCount"`
	PermissionCount int64          `json:"permissionCount"`
}

func (q *Queries) ListRolesWithCountsByServiceID(ctx context.Context, arg ListRolesWithCountsByServiceIDParams) ([]ListRolesWithCountsByServiceIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listRolesWithCountsByServiceID, arg.ServiceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRolesWithCountsByServiceIDRow
	for rows.Next() {
		var i ListRolesWithCountsByServiceIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Name,
			&i.Description,
			&i.IsGlobal,
			&i.CreatedAt,
			&i.UserCount,
			&i.PermissionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsedPermissionIDsForRole = `-- name: ListUsedPermissionIDsForRole :many
SELECT
	permission_id
FROM
	role_permissions
WHERE
	role_id = ?
`

func (q *Queries) ListUsedPermissionIDsForRole(ctx context.Context, roleID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listUsedPermissionIDsForRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var permission_id string
		if err := rows.Scan(&permission_id); err != nil {
			return nil, err
		}
		items = append(items, permission_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWithRole = `-- name: ListUsersWithRole :many
SELECT
	u.id,
	u.name,
	u.surname,
	u.patronymic,
	u.username,
	u.gender_id,
	u.birthday,
	u.status,
	u.created_at
FROM
	users u
	JOIN user_roles ur ON ur.user_id = u.id
WHERE
	ur.role_id = ?
`

type ListUsersWithRoleRow struct {
	ID         string         `json:"id"`
	Name       string         `json:"name"`
	Surname    string         `json:"surname"`
	Patronymic sql.NullString `json:"patronymic"`
	Username   string         `json:"username"`
	GenderID   string         `json:"genderId"`
	Birthday   time.Time      `json:"birthday"`
	Status     UsersStatus    `json:"status"`
	CreatedAt  time.Time      `json:"createdAt"`
}

func (q *Queries) ListUsersWithRole(ctx context.Context, roleID string) ([]ListUsersWithRoleRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsersWithRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersWithRoleRow
	for rows.Next() {
		var i ListUsersWithRoleRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Surname,
			&i.Patronymic,
			&i.Username,
			&i.GenderID,
			&i.Birthday,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePermissionFromRole = `-- name: RemovePermissionFromRole :exec
DELETE FROM role_permissions
WHERE
	role_id = ?
	AND permission_id = ?
`

type RemovePermissionFromRoleParams struct {
	RoleID       string `json:"roleId"`
	PermissionID string `json:"permissionId"`
}

func (q *Queries) RemovePermissionFromRole(ctx context.Context, arg RemovePermissionFromRoleParams) error {
	_, err := q.db.ExecContext(ctx, removePermissionFromRole, arg.RoleID, arg.PermissionID)
	return err
}

const updateRole = `-- name: UpdateRole :exec
UPDATE roles
SET
	service_id = ?,
	name = ?,
	description = ?,
	is_global = ?
WHERE
	id = ?
`

type UpdateRoleParams struct {
	ServiceID   sql.NullString `json:"serviceId"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	IsGlobal    bool           `json:"isGlobal"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateRole,
		arg.ServiceID,
		arg.Name,
		arg.Description,
		arg.IsGlobal,
		arg.ID,
	)
	return err
}
