// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package repo

import (
	"context"
	"database/sql"
	"time"
)

const countServices = `-- name: CountServices :one
SELECT COUNT(*) AS total
FROM services
`

func (q *Queries) CountServices(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countServices)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createService = `-- name: CreateService :exec
INSERT INTO services (id, name, description, image_url, url, theme, prefix, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, NOW())
`

type CreateServiceParams struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	ImageUrl    sql.NullString `json:"imageUrl"`
	Url         sql.NullString `json:"url"`
	Theme       sql.NullString `json:"theme"`
	Prefix      string         `json:"prefix"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) error {
	_, err := q.db.ExecContext(ctx, createService,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ImageUrl,
		arg.Url,
		arg.Theme,
		arg.Prefix,
	)
	return err
}

const deleteService = `-- name: DeleteService :exec
DELETE FROM services
WHERE id = ?
`

func (q *Queries) DeleteService(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteService, id)
	return err
}

const getServiceByAPIKeyHash = `-- name: GetServiceByAPIKeyHash :one
SELECT id, name, description, image_url, url, theme, prefix, api_key_hash, created_at
FROM services
WHERE api_key_hash = ?
`

type GetServiceByAPIKeyHashRow struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	ImageUrl    sql.NullString `json:"imageUrl"`
	Url         sql.NullString `json:"url"`
	Theme       sql.NullString `json:"theme"`
	Prefix      string         `json:"prefix"`
	ApiKeyHash  sql.NullString `json:"apiKeyHash"`
	CreatedAt   time.Time      `json:"createdAt"`
}

func (q *Queries) GetServiceByAPIKeyHash(ctx context.Context, apiKeyHash sql.NullString) (GetServiceByAPIKeyHashRow, error) {
	row := q.db.QueryRowContext(ctx, getServiceByAPIKeyHash, apiKeyHash)
	var i GetServiceByAPIKeyHashRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.Url,
		&i.Theme,
		&i.Prefix,
		&i.ApiKeyHash,
		&i.CreatedAt,
	)
	return i, err
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT id, name, description, image_url, url, theme, prefix, api_key_hash, created_at
FROM services
WHERE id = ?
`

type GetServiceByIDRow struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	ImageUrl    sql.NullString `json:"imageUrl"`
	Url         sql.NullString `json:"url"`
	Theme       sql.NullString `json:"theme"`
	Prefix      string         `json:"prefix"`
	ApiKeyHash  sql.NullString `json:"apiKeyHash"`
	CreatedAt   time.Time      `json:"createdAt"`
}

func (q *Queries) GetServiceByID(ctx context.Context, id string) (GetServiceByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getServiceByID, id)
	var i GetServiceByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.Url,
		&i.Theme,
		&i.Prefix,
		&i.ApiKeyHash,
		&i.CreatedAt,
	)
	return i, err
}

const listServices = `-- name: ListServices :many
SELECT id, name, description, image_url, url, theme, prefix, api_key_hash, created_at
FROM services
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListServicesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListServicesRow struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	ImageUrl    sql.NullString `json:"imageUrl"`
	Url         sql.NullString `json:"url"`
	Theme       sql.NullString `json:"theme"`
	Prefix      string         `json:"prefix"`
	ApiKeyHash  sql.NullString `json:"apiKeyHash"`
	CreatedAt   time.Time      `json:"createdAt"`
}

func (q *Queries) ListServices(ctx context.Context, arg ListServicesParams) ([]ListServicesRow, error) {
	rows, err := q.db.QueryContext(ctx, listServices, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListServicesRow
	for rows.Next() {
		var i ListServicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ImageUrl,
			&i.Url,
			&i.Theme,
			&i.Prefix,
			&i.ApiKeyHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesByUserID = `-- name: ListServicesByUserID :many
SELECT DISTINCT s.id, s.name, s.description, s.image_url, s.url, s.theme, s.prefix, s.api_key_hash, s.created_at
FROM services s
JOIN roles r ON (r.service_id = s.id OR r.service_id IS NULL)
JOIN user_roles ur ON ur.role_id = r.id
WHERE ur.user_id = ?
`

type ListServicesByUserIDRow struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	ImageUrl    sql.NullString `json:"imageUrl"`
	Url         sql.NullString `json:"url"`
	Theme       sql.NullString `json:"theme"`
	Prefix      string         `json:"prefix"`
	ApiKeyHash  sql.NullString `json:"apiKeyHash"`
	CreatedAt   time.Time      `json:"createdAt"`
}

// Сервисы, доступные пользователю через его роли:
// либо роль привязана к конкретному сервису, либо роль глобальная (service_id IS NULL).
func (q *Queries) ListServicesByUserID(ctx context.Context, userID string) ([]ListServicesByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listServicesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListServicesByUserIDRow
	for rows.Next() {
		var i ListServicesByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ImageUrl,
			&i.Url,
			&i.Theme,
			&i.Prefix,
			&i.ApiKeyHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeServiceAPIKey = `-- name: RevokeServiceAPIKey :exec
UPDATE services
SET api_key_hash = NULL
WHERE id = ?
`

func (q *Queries) RevokeServiceAPIKey(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, revokeServiceAPIKey, id)
	return err
}

const setServiceAPIKeyHash = `-- name: SetServiceAPIKeyHash :exec
UPDATE services
SET api_key_hash = ?
WHERE id = ?
`

type SetServiceAPIKeyHashParams struct {
	ApiKeyHash sql.NullString `json:"apiKeyHash"`
	ID         string         `json:"id"`
}

func (q *Queries) SetServiceAPIKeyHash(ctx context.Context, arg SetServiceAPIKeyHashParams) error {
	_, err := q.db.ExecContext(ctx, setServiceAPIKeyHash, arg.ApiKeyHash, arg.ID)
	return err
}

const updateService = `-- name: UpdateService :exec
UPDATE services
SET name        = ?,
    description = ?,
    image_url   = ?,
    url         = ?,
    theme       = ?,
    prefix      = ?
WHERE id = ?
`

type UpdateServiceParams struct {
	Name        string         `json:"name"`
	Description string         `json:"description"`
	ImageUrl    sql.NullString `json:"imageUrl"`
	Url         sql.NullString `json:"url"`
	Theme       sql.NullString `json:"theme"`
	Prefix      string         `json:"prefix"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) error {
	_, err := q.db.ExecContext(ctx, updateService,
		arg.Name,
		arg.Description,
		arg.ImageUrl,
		arg.Url,
		arg.Theme,
		arg.Prefix,
		arg.ID,
	)
	return err
}
