// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: smtp_settings.sql

package repo

import (
	"context"
	"database/sql"
)

const getSMTPSettings = `-- name: GetSMTPSettings :one
SELECT
	id,
	host,
	port,
	username,
	password_encrypted,
	from_address,
	from_name,
	use_tls,
	updated_at
FROM
	smtp_settings
WHERE
	id = ?
`

// Синглтон: ровно одна строка, id фиксирован на стороне Go (settings.SingletonID).
func (q *Queries) GetSMTPSettings(ctx context.Context, id string) (SmtpSetting, error) {
	row := q.db.QueryRowContext(ctx, getSMTPSettings, id)
	var i SmtpSetting
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.PasswordEncrypted,
		&i.FromAddress,
		&i.FromName,
		&i.UseTls,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSMTPSettings = `-- name: UpsertSMTPSettings :exec
INSERT INTO
	smtp_settings (id, host, port, username, password_encrypted, from_address, from_name, use_tls)
VALUES
	(?, ?, ?, ?, ?, ?, ?, ?) ON DUPLICATE KEY
UPDATE host =
VALUES
	(host),
	port =
VALUES
	(port),
	username =
VALUES
	(username),
	password_encrypted =
VALUES
	(password_encrypted),
	from_address =
VALUES
	(from_address),
	from_name =
VALUES
	(from_name),
	use_tls =
VALUES
	(use_tls)
`

type UpsertSMTPSettingsParams struct {
	ID                string         `json:"id"`
	Host              string         `json:"host"`
	Port              int32          `json:"port"`
	Username          string         `json:"username"`
	PasswordEncrypted string         `json:"passwordEncrypted"`
	FromAddress       string         `json:"fromAddress"`
	FromName          sql.NullString `json:"fromName"`
	UseTls            bool           `json:"useTls"`
}

func (q *Queries) UpsertSMTPSettings(ctx context.Context, arg UpsertSMTPSettingsParams) error {
	_, err := q.db.ExecContext(ctx, upsertSMTPSettings,
		arg.ID,
		arg.Host,
		arg.Port,
		arg.Username,
		arg.PasswordEncrypted,
		arg.FromAddress,
		arg.FromName,
		arg.UseTls,
	)
	return err
}
