// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package repo

import (
	"context"
	"database/sql"
	"time"
)

const addRoleToUser = `-- name: AddRoleToUser :exec
INSERT INTO
	user_roles (user_id, role_id)
VALUES
	(?, ?)
`

type AddRoleToUserParams struct {
	UserID string `json:"userId"`
	RoleID string `json:"roleId"`
}

func (q *Queries) AddRoleToUser(ctx context.Context, arg AddRoleToUserParams) error {
	_, err := q.db.ExecContext(ctx, addRoleToUser, arg.UserID, arg.RoleID)
	return err
}

const countUsers = `-- name: CountUsers :one
SELECT
	COUNT(*) AS total
FROM
	users u
WHERE
	CAST(? AS char) IS NULL
	OR u.name LIKE CONCAT('%', CAST(? AS char), '%')
	OR u.surname LIKE CONCAT('%', CAST(? AS char), '%')
	OR u.patronymic LIKE CONCAT('%', CAST(? AS char), '%')
	OR u.username LIKE CONCAT('%', CAST(? AS char), '%')
`

type CountUsersParams struct {
	Search interface{} `json:"search"`
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers,
		arg.Search,
		arg.Search,
		arg.Search,
		arg.Search,
		arg.Search,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countUsersByServiceID = `-- name: CountUsersByServiceID :one
SELECT
	COUNT(DISTINCT u.id) AS total
FROM
	users u
	JOIN user_roles ur ON ur.user_id = u.id
	JOIN roles r ON r.id = ur.role_id
WHERE
	r.service_id = ?
	AND (
		CAST(? AS char) IS NULL
		OR u.name LIKE CONCAT('%', CAST(? AS char), '%')
		OR u.surname LIKE CONCAT('%', CAST(? AS char), '%')
		OR u.patronymic LIKE CONCAT('%', CAST(? AS char), '%')
		OR u.username LIKE CONCAT('%', CAST(? AS char), '%')
	)
`

type CountUsersByServiceIDParams struct {
	ServiceID sql.NullString `json:"serviceId"`
	Search    interface{}    `json:"search"`
}

func (q *Queries) CountUsersByServiceID(ctx context.Context, arg CountUsersByServiceIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsersByServiceID,
		arg.ServiceID,
		arg.Search,
		arg.Search,
		arg.Search,
		arg.Search,
		arg.Search,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO
	users (id, name, surname, patronymic, username, gender_id, birthday, password, status, created_at)
VALUES
	(?, ?, ?, ?, ?, ?, ?, ?, ?, NOW())
`

type CreateUserParams struct {
	ID         string         `json:"id"`
	Name       string         `json:"name"`
	Surname    string         `json:"surname"`
	Patronymic sql.NullString `json:"patronymic"`
	Username   string         `json:"username"`
	GenderID   string         `json:"genderId"`
	Birthday   time.Time      `json:"birthday"`
	Password   string         `json:"password"`
	Status     UsersStatus    `json:"status"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Surname,
		arg.Patronymic,
		arg.Username,
		arg.GenderID,
		arg.Birthday,
		arg.Password,
		arg.Status,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE
	id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
	id,
	name,
	surname,
	patronymic,
	username,
	gender_id,
	birthday,
	password,
	status,
	created_at
FROM
	users
WHERE
	id = ?
`

type GetUserByIDRow struct {
	ID         string         `json:"id"`
	Name       string         `json:"name"`
	Surname    string         `json:"surname"`
	Patronymic sql.NullString `json:"patronymic"`
	Username   string         `json:"username"`
	GenderID   string         `json:"genderId"`
	Birthday   time.Time      `json:"birthday"`
	Password   string         `json:"password"`
	Status     UsersStatus    `json:"status"`
	CreatedAt  time.Time      `json:"createdAt"`
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Patronymic,
		&i.Username,
		&i.GenderID,
		&i.Birthday,
		&i.Password,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT
	id,
	name,
	surname,
	patronymic,
	username,
	gender_id,
	birthday,
	password,
	status,
	created_at
FROM
	users
WHERE
	username = ?
`

type GetUserByUsernameRow struct {
	ID         string         `json:"id"`
	Name       string         `json:"name"`
	Surname    string         `json:"surname"`
	Patronymic sql.NullString `json:"patronymic"`
	Username   string         `json:"username"`
	GenderID   string         `json:"genderId"`
	Birthday   time.Time      `json:"birthday"`
	Password   string         `json:"password"`
	Status     UsersStatus    `json:"status"`
	CreatedAt  time.Time      `json:"createdAt"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Patronymic,
		&i.Username,
		&i.GenderID,
		&i.Birthday,
		&i.Password,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT
	id,
	name,
	surname,
	patronymic,
	username,
	gender_id,
	birthday,
	password,
	status,
	created_at
FROM
	users
ORDER BY
	created_at DESC
`

type ListAllUsersRow struct {
	ID         string         `json:"id"`
	Name       string         `json:"name"`
	Surname    string         `json:"surname"`
	Patronymic sql.NullString `json:"patronymic"`
	Username   string         `json:"username"`
	GenderID   string         `json:"genderId"`
	Birthday   time.Time      `json:"birthday"`
	Password   string         `json:"password"`
	Status     UsersStatus    `json:"status"`
	CreatedAt  time.Time      `json:"createdAt"`
}

func (q *Queries) ListAllUsers(ctx context.Context) ([]ListAllUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllUsersRow
	for rows.Next() {
		var i ListAllUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Surname,
			&i.Patronymic,
			&i.Username,
			&i.GenderID,
			&i.Birthday,
			&i.Password,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesForUser = `-- name: ListRolesForUser :many
SELECT
	r.id,
	r.service_id,
	r.name,
	r.description,
	r.is_global,
	r.created_at
FROM
	roles r
	JOIN user_roles ur ON ur.role_id = r.id
WHERE
	ur.user_id = ?
`

func (q *Queries) ListRolesForUser(ctx context.Context, userID string) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, listRolesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Name,
			&i.Description,
			&i.IsGlobal,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT
	id,
	name,
	surname,
	patronymic,
	username,
	gender_id,
	birthday,
	password,
	status,
	created_at
FROM
	users u
WHERE
	CAST(? AS char) IS NULL
	OR u.name LIKE CONCAT('%', CAST(? AS char), '%')
	OR u.surname LIKE CONCAT('%', CAST(? AS char), '%')
	OR u.patronymic LIKE CONCAT('%', CAST(? AS char), '%')
	OR u.username LIKE CONCAT('%', CAST(? AS char), '%')
ORDER BY
	CASE
		WHEN CAST(? AS char) = 'asc' THEN CASE CAST(? AS char)
			WHEN 'name' THEN CAST(u.name AS char)
			WHEN 'surname' THEN CAST(u.surname AS char)
			WHEN 'patronymic' THEN CAST(u.patronymic AS char)
			WHEN 'username' THEN CAST(u.username AS char)
			WHEN 'birthday' THEN CAST(u.birthday AS char)
			WHEN 'status' THEN CAST(u.status AS char)
			ELSE CAST(u.created_at AS char)
		END
	END ASC,
	CASE
		WHEN CAST(? AS char) = 'desc' THEN CASE CAST(? AS char)
			WHEN 'name' THEN CAST(u.name AS char)
			WHEN 'surname' THEN CAST(u.surname AS char)
			WHEN 'patronymic' THEN CAST(u.patronymic AS char)
			WHEN 'username' THEN CAST(u.username AS char)
			WHEN 'birthday' THEN CAST(u.birthday AS char)
			WHEN 'status' THEN CAST(u.status AS char)
			ELSE CAST(u.created_at AS char)
		END
	END DESC
LIMIT
	?
OFFSET
	?
`

type ListUsersParams struct {
	Search  interface{} `json:"search"`
	SortDir interface{} `json:"sortDir"`
	SortBy  interface{} `json:"sortBy"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type ListUsersRow struct {
	ID         string         `json:"id"`
	Name       string         `json:"name"`
	Surname    string         `json:"surname"`
	Patronymic sql.NullString `json:"patronymic"`
	Username   string         `json:"username"`
	GenderID   string         `json:"genderId"`
	Birthday   time.Time      `json:"birthday"`
	Password   string         `json:"password"`
	Status     UsersStatus    `json:"status"`
	CreatedAt  time.Time      `json:"createdAt"`
}

// search: поиск по name/surname/patronymic/username. sort_by: name/surname/
// patronymic/username/birthday/status/created_at (иначе created_at),
// sort_dir: asc (иначе desc) — см. query.QuerySort.
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers,
		arg.Search,
		arg.Search,
		arg.Search,
		arg.Search,
		arg.Search,
		arg.SortDir,
		arg.SortBy,
		arg.SortDir,
		arg.SortBy,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Surname,
			&i.Patronymic,
			&i.Username,
			&i.GenderID,
			&i.Birthday,
			&i.Password,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByServiceID = `-- name: ListUsersByServiceID :many
SELECT DISTINCT
	u.id,
	u.name,
	u.surname,
	u.patronymic,
	u.username,
	u.gender_id,
	u.birthday,
	u.password,
	u.status,
	u.created_at
FROM
	users u
	JOIN user_roles ur ON ur.user_id = u.id
	JOIN roles r ON r.id = ur.role_id
WHERE
	r.service_id = ?
	AND (
		CAST(? AS char) IS NULL
		OR u.name LIKE CONCAT('%', CAST(? AS char), '%')
		OR u.surname LIKE CONCAT('%', CAST(? AS char), '%')
		OR u.patronymic LIKE CONCAT('%', CAST(? AS char), '%')
		OR u.username LIKE CONCAT('%', CAST(? AS char), '%')
	)
ORDER BY
	CASE
		WHEN CAST(? AS char) = 'asc' THEN CASE CAST(? AS char)
			WHEN 'name' THEN CAST(u.name AS char)
			WHEN 'surname' THEN CAST(u.surname AS char)
			WHEN 'patronymic' THEN CAST(u.patronymic AS char)
			WHEN 'username' THEN CAST(u.username AS char)
			WHEN 'birthday' THEN CAST(u.birthday AS char)
			WHEN 'status' THEN CAST(u.status AS char)
			ELSE CAST(u.created_at AS char)
		END
	END ASC,
	CASE
		WHEN CAST(? AS char) = 'desc' THEN CASE CAST(? AS char)
			WHEN 'name' THEN CAST(u.name AS char)
			WHEN 'surname' THEN CAST(u.surname AS char)
			WHEN 'patronymic' THEN CAST(u.patronymic AS char)
			WHEN 'username' THEN CAST(u.username AS char)
			WHEN 'birthday' THEN CAST(u.birthday AS char)
			WHEN 'status' THEN CAST(u.status AS char)
			ELSE CAST(u.created_at AS char)
		END
	END DESC
LIMIT
	?
OFFSET
	?
`

type ListUsersByServiceIDParams struct {
	ServiceID sql.NullString `json:"serviceId"`
	Search    interface{}    `json:"search"`
	SortDir   interface{}    `json:"sortDir"`
	SortBy    interface{}    `json:"sortBy"`
	Limit     int32          `json:"limit"`
	Offset    int32          `json:"offset"`
}

type ListUsersByServiceIDRow struct {
	ID         string         `json:"id"`
	Name       string         `json:"name"`
	Surname    string         `json:"surname"`
	Patronymic sql.NullString `json:"patronymic"`
	Username   string         `json:"username"`
	GenderID   string         `json:"genderId"`
	Birthday   time.Time      `json:"birthday"`
	Password   string         `json:"password"`
	Status     UsersStatus    `json:"status"`
	CreatedAt  time.Time      `json:"createdAt"`
}

func (q *Queries) ListUsersByServiceID(ctx context.Context, arg ListUsersByServiceIDParams) ([]ListUsersByServiceIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsersByServiceID,
		arg.ServiceID,
		arg.Search,
		arg.Search,
		arg.Search,
		arg.Search,
		arg.Search,
		arg.SortDir,
		arg.SortBy,
		arg.SortDir,
		arg.SortBy,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersByServiceIDRow
	for rows.Next() {
		var i ListUsersByServiceIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Surname,
			&i.Patronymic,
			&i.Username,
			&i.GenderID,
			&i.Birthday,
			&i.Password,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRoleFromUser = `-- name: RemoveRoleFromUser :exec
DELETE FROM user_roles
WHERE
	user_id = ?
	AND role_id = ?
`

type RemoveRoleFromUserParams struct {
	UserID string `json:"userId"`
	RoleID string `json:"roleId"`
}

func (q *Queries) RemoveRoleFromUser(ctx context.Context, arg RemoveRoleFromUserParams) error {
	_, err := q.db.ExecContext(ctx, removeRoleFromUser, arg.UserID, arg.RoleID)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET
	name = COALESCE(?, name),
	surname = COALESCE(?, surname),
	patronymic = COALESCE(?, patronymic),
	username = COALESCE(?, username),
	birthday = COALESCE(?, birthday),
	status = COALESCE(?, status),
	gender_id = COALESCE(?, gender_id),
	password = COALESCE(?, password)
WHERE
	id = ?
`

type UpdateUserParams struct {
	Name       sql.NullString  `json:"name"`
	Surname    sql.NullString  `json:"surname"`
	Patronymic sql.NullString  `json:"patronymic"`
	Username   sql.NullString  `json:"username"`
	Birthday   sql.NullTime    `json:"birthday"`
	Status     NullUsersStatus `json:"status"`
	GenderID   sql.NullString  `json:"genderId"`
	Password   sql.NullString  `json:"password"`
	ID         string          `json:"id"`
}

// Частичное обновление: sqlc.narg-поля, для которых передан NULL, остаются без изменений.
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Name,
		arg.Surname,
		arg.Patronymic,
		arg.Username,
		arg.Birthday,
		arg.Status,
		arg.GenderID,
		arg.Password,
		arg.ID,
	)
	return err
}
